version: "3.9"

services:
  mangaManagerApi:
    build: ./mangaManager
    container_name: mangaManager
    ports:
      - "8080:8080"
    networks:
      - app-net

  apiTest:
    build: ./apiTest
    container_name: apiTest
    depends_on:
      - mangaManagerApi
    networks:
      - app-net
networks:
  app-net:
    driver: bridge
