services:
  mangamanagerapi:
    build: ./mangaManager
    container_name: mangamanagerapi
    ports:
      - "8080:8080"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z localhost 8080" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  apitest:
    build: ./apiTest
    container_name: apitest
    depends_on:
      mangamanagerapi:
        condition: service_healthy
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
